version: '3.8'
services:
  dbs.demo_springboot:
    image: adoptopenjdk:8-jdk-openj9
    command: java -jar /home/demo/democours.jar
    volumes:
      - "../target:/home/demo"
    ports:
      - "8090:8080"
  dbs.db_test:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db_test
      - POSTGRES_USER=dmissud
      - POSTGRES_PASSWORD=garage